app = "gemini-openai-proxy"
primary_region = "lax"

[build]
dockerfile = "docker/Dockerfile_deno"

[env]

[processes]

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "512MB"

[[services.http_checks]]
interval = "1m"
method = "get"
path = "/"
protocol = "https"
timeout = "5s"
