name: biome check

permissions:
  contents: read
  packages: write

on:
  push:
  workflow_dispatch:

jobs:
  delete-untagged-images:
    name: Delete Untagged Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome CLI
        uses: biomejs/setup-biome@v2
      - name: Run Biome
        run: biome ci .
