name: Remove Untagged Image

on:
  # every sunday at 00:00
  schedule:
    - cron: "0 0 * * SUN"
  # or manually
  workflow_dispatch:

jobs:
  delete-untagged-images:
    name: Delete Untagged Images
    runs-on: ubuntu-latest
    steps:
      - uses: camargo/delete-untagged-action@v1
        with:
          github-token: ${{ secrets.DELETE_PACKAGES_TOKEN }}
          personal-account: true
